// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW0y4T9xzl8Tn-XJ5FYHThjCcGV5kHa6s',
    appId: '1:803915294344:web:ffc371420002515e35613d',
    messagingSenderId: '803915294344',
    projectId: 'delivery-app-c21cb',
    authDomain: 'delivery-app-c21cb.firebaseapp.com',
    storageBucket: 'delivery-app-c21cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQEN2qKK2xOYxgSguSxbZ_Fut05odNTp4',
    appId: '1:803915294344:android:497efe76d2909bf935613d',
    messagingSenderId: '803915294344',
    projectId: 'delivery-app-c21cb',
    storageBucket: 'delivery-app-c21cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYp_Mr_Hkd6LaEpSpx0Xdcj9gt8nxOIMw',
    appId: '1:803915294344:ios:02a5c4a3633d95f635613d',
    messagingSenderId: '803915294344',
    projectId: 'delivery-app-c21cb',
    storageBucket: 'delivery-app-c21cb.firebasestorage.app',
    iosBundleId: 'com.example.deliveryAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYp_Mr_Hkd6LaEpSpx0Xdcj9gt8nxOIMw',
    appId: '1:803915294344:ios:02a5c4a3633d95f635613d',
    messagingSenderId: '803915294344',
    projectId: 'delivery-app-c21cb',
    storageBucket: 'delivery-app-c21cb.firebasestorage.app',
    iosBundleId: 'com.example.deliveryAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW0y4T9xzl8Tn-XJ5FYHThjCcGV5kHa6s',
    appId: '1:803915294344:web:300de46a7f2dbc9f35613d',
    messagingSenderId: '803915294344',
    projectId: 'delivery-app-c21cb',
    authDomain: 'delivery-app-c21cb.firebaseapp.com',
    storageBucket: 'delivery-app-c21cb.firebasestorage.app',
  );
}
